#!/bin/sh

java  -server -Dapple.awt.graphics.UseQuartz=true -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -classpath "./bin:./jar:./jar/quaqua.jar:./jar/:bin:jar/JTransforms-3.0.jar:jar/JLargeArrays-1.2.jar"  OptiExFrame  $@
